FROM ubuntu

RUN apt-get update
RUN apt-get install -y python && python-pip
RUN pip install flask
RUN pip install -U scikit-learn
RUN pip install pandas

COPY . /appFol

WORKDIR /appFol

CMD python /appFol/app.py